[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[project]
name = 'pygit2'
version = '1.13.3'
description = 'Python bindings for libgit2.'
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Programming Language :: Python :: Implementation :: CPython',
    'Topic :: Software Development :: Version Control',
]
dependencies = ['cffi>=1.16.0']
keywords = ['git']
license = {text = 'GPLv2 with linking exception'}
maintainers = [{name = 'J. David Ibáñez', email = 'jdavid.ibp@gmail.com'}]
readme = 'README.rst'
requires-python = '>=3.9'

[project.urls]
Homepage = 'https://github.com/libgit2/pygit2'
Documentation = 'https://www.pygit2.org/'
Changelog = 'https://github.com/libgit2/pygit2/blob/master/CHANGELOG.rst'
Funding = 'https://github.com/sponsors/jdavid'

[tool.cibuildwheel]
enable = ["pypy"]
skip = "*musllinux_aarch64 *musllinux_ppc64le"

archs = ["native"]
build-frontend = "default"
dependency-versions = "pinned"
environment = {LIBGIT2_VERSION="1.9.0", LIBSSH2_VERSION="1.11.1", OPENSSL_VERSION="3.2.3", LIBGIT2="/project/ci"}

before-all = "sh build.sh"

[tool.cibuildwheel.linux]
repair-wheel-command = "LD_LIBRARY_PATH=/project/ci/lib64 auditwheel repair -w {dest_dir} {wheel}"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
repair-wheel-command = "LD_LIBRARY_PATH=/project/ci/lib auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
archs = ["universal2"]
environment = {LIBGIT2_VERSION="1.9.0", LIBSSH2_VERSION="1.11.1", OPENSSL_VERSION="3.2.3", LIBGIT2="/Users/runner/work/pygit2/pygit2/ci"}
repair-wheel-command = "DYLD_LIBRARY_PATH=/Users/runner/work/pygit2/pygit2/ci/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}"

[tool.ruff]
target-version = "py310"  # oldest supported Python version
fix = true
extend-exclude = [
    ".cache",
    ".coverage",
    "build",
    "venv*",
]

[tool.ruff.format]
quote-style = "single"

[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git*'
check-hidden = true
# ignore-regex = ''
ignore-words-list = 'devault,claus'
